### ISSUE TITLE
CI does not run on Windows or macOS

### ISSUE THREAD

**Issue by agateau-gg** [GitGuardian/ggshield#168]
There is an issue with our CI setup, which make it run all jobs on Linux:

![image](https://user-images.githubusercontent.com/91945295/151414892-a13061ec-1835-497a-858b-330eb5c29412.png)

![image](https://user-images.githubusercontent.com/91945295/151414942-6d5cf749-a044-42ed-978a-f2200060c8a7.png)

## TODO

There is quite some work to do here, so it's better to do it in separate steps.

- [x] Make CI run on Windows and macOS (#164)
- [x] Fix test_text_output (#180)
- [x] Fix test_scan_docker (#204)
- [x] #461
