### ISSUE TITLE
Move Files.extra_headers to extra_headers module

### ISSUE THREAD

**Issue by agateau-gg** [GitGuardian/ggshield#233]
## Description

The Files class currently has an [extra_headers](https://github.com/GitGuardian/ggshield/blob/18a72e5c85ba6364c0fed9387ddd19456bb2ad9d/ggshield/scan/scannable.py#L116) property whose job is to add the `GGShield-Version` and `GGShield-Command-Path` HTTP headers. 

This property should not be part of the Files class: it is not specific to Files instances (has can be noticed by the fact that it does not use its `self` argument) and could be used in other situations.

The [iac_scan()](https://github.com/GitGuardian/ggshield/blob/main/ggshield/cmd/iac/scan.py#L153) function has a copy of this code. It should be factorized.

## TODO

- [ ] Implement the work done by this property in the `get_extra_headers()` function of the `core.extra_headers` module.
- [ ] Remove the property.
- [ ] Make `iac_scan()` use `get_extra_headers()`.
