### ISSUE TITLE
Add functional tests

### ISSUE THREAD

**Issue by agateau-gg** [GitGuardian/ggshield#350]
## Description

ggshield has good unit-test coverage, but it lacks functional tests: tests which test the whole product, end-to-end, performing real scans with real API requests.

This can be implemented using pytest by making it run the ggshield command.

These tests will be slow. It's OK. To ensure this does not make it painful to run other tests while developing we can keep them in a separate directory.

There is a work-in-progress branch implementing these tests in <https://github.com/agateau-gg/ggshield/tree/agateau/functests>. Tests are in the `functests` directory. They can be run with `pytest functest`.

The goal of this issue is to integrate this branch.

## Tasks

- [ ] Measure coverage, add missing commands and/or create issues to add them.
- [ ] Make CI run functional tests. We can run them on all PRs for now, but we may have to revisit this later if they start to take too long.
- [ ] Document the functional tests in CONTRIBUTE.md.
