### ISSUE TITLE
pre-commit hook does not work in Visual Studio

### ISSUE THREAD

**Issue by agateau-gg** [GitGuardian/ggshield#467]
## Environment

- ggshield version: 1.14.2
- Operating system (Linux, macOS, Windows): Windows
- Operating system version: 11
- Python version: any

## Describe the bug

Visual Studio (Not VS Code!) fails to execute our pre-commit hook because it cannot execute our shebang (`#!/usr/bin/env bash`).

Steps to reproduce:

1. Install a global pre-commit hook with `ggshield install -t pre-commit -m global`
2. Start Visual Studio
3. Try to commit from within Visual Studio

Actual result:

![Visual Studio error message](https://user-images.githubusercontent.com/91945295/215992513-d45240ec-c1e6-435f-bfee-abac40616ec0.png)

Expected result:

Pre-commit hook should run and commit should be scanned.

One can workaround that by replacing the shebang with `#!/bin/sh`. However it's not a correct fix because the hook uses bash-specific syntax so it would fail on OS where /bin/sh is not bash, such as Ubuntu.

## TODO

- [ ] Replace all our hook shebangs with `#!/bin/sh`
- [ ] Fix the bashims
- [ ] If possible, setup a check like check-bashism in the CI

**Comment by pierrelalanne** [comment]
I am not sure to understand why this issue is limited to Visual Studio users ?  
From my understanding, any user with the global pre-commit hook installed but without bash available will fail to execute the hook ?

**Comment by agateau-gg** [comment]
I think that's because VS ships with its own version of Git, which wrongly assumes that a script to be executed with bash must be Linux only, so it must go through WSL.
